import type { ProductChannel, Role } from './types';

// Lowercase keyword lists. Phrases use word-boundary matching in score.ts.
// Tune freely — this file is meant to be edited by the team.

export const ROLE_KEYWORDS: Record<Role, string[]> = {
  manager: [
    'roadmap',
    'strategy',
    'leadership',
    'org',
    'reorg',
    'layoff',
    'hiring',
    'pricing',
    'ga',
    'general availability',
    'announce',
    'announcement',
    'partnership',
    'acquisition',
    'earnings',
    'snowflake',
    'databricks',
    'bigquery',
    'aws',
    'gcp',
    'gartner',
    'forrester',
    'idc',
    'market share',
    'enterprise',
    // adjacent
    'q1 results',
    'q2 results',
    'q3 results',
    'q4 results',
    'satya nadella',
    'investment',
    'funding round',
  ],
  developer: [
    'api',
    'sdk',
    'library',
    'framework',
    'release',
    'open source',
    'oss',
    'github',
    'typescript',
    'javascript',
    'python',
    'rust',
    '.net',
    'c#',
    'spark',
    'm language',
    'power query m',
    'dax',
    'connector',
    'performance',
    'benchmark',
    'compiler',
    'runtime',
    'cli',
    'developer experience',
    'devex',
    'tooling',
    // adjacent
    'go ',
    'kotlin',
    'react',
    'next.js',
    'wasm',
    'webassembly',
    'package manager',
    'monorepo',
    'lsp',
    'language server',
    'static analysis',
  ],
  sre: [
    'incident',
    'outage',
    'postmortem',
    'post-mortem',
    'reliability',
    'observability',
    'monitoring',
    'sre',
    'on-call',
    'on call',
    'kubernetes',
    'k8s',
    'scaling',
    'latency',
    'sli',
    'slo',
    'security',
    'cve',
    'vulnerability',
    'patch',
    'azure status',
    'service health',
    'capacity',
    'chaos engineering',
    // adjacent
    'opentelemetry',
    'otel',
    'prometheus',
    'grafana',
    'terraform',
    'helm',
    'service mesh',
    'istio',
    'linkerd',
    'rate limit',
    'circuit breaker',
    'blast radius',
    'autoscaling',
    'load shedding',
  ],
  pm: [
    'feature',
    'preview',
    'public preview',
    'private preview',
    'general availability',
    'roadmap',
    'customer',
    'use case',
    'case study',
    'analyst',
    'gartner',
    'forrester',
    'competitive',
    'positioning',
    'ux',
    'user research',
    'design',
    'persona',
    'adoption',
    'retention',
    'pricing',
    // adjacent
    'beta',
    'launch',
    'launching',
    'shipping',
    'go-to-market',
    'gtm',
    'product market fit',
    'pmf',
    'okrs',
    'north star',
  ],
};

// Product-specific keyword lists. Order doesn't matter; matches are additive.
// Tier 1 = direct product/feature names. Tier 2 = adjacent concepts that
// strongly imply the product even if it's not named. Both are matched the
// same way; the split is just for readability.
export const PRODUCT_KEYWORDS: Record<ProductChannel, string[]> = {
  'power-query': [
    // direct
    'power query',
    'pqo',
    'power query online',
    'm language',
    'm formula',
    // adjacent
    'mashup engine',
    'query folding',
    'data connector',
  ],
  dataflows: [
    'dataflow',
    'dataflows',
    'dataflow gen2',
    'dataflows gen1',
    // adjacent
    'etl',
    'elt',
    'data preparation',
    'data prep',
    'data wrangling',
    'data transformation',
    'low-code data',
  ],
  fabric: [
    'microsoft fabric',
    'fabric capacity',
    'fabric workspace',
    'ms fabric',
    // adjacent / competitive landscape
    'unified analytics',
    'analytics platform',
    'lakehouse platform',
    'snowflake',
    'databricks',
    'bigquery',
    'redshift',
    'databricks lakehouse',
    'snowflake cortex',
  ],
  'data-factory': [
    'data factory',
    'adf',
    'azure data factory',
    'fabric data factory',
    // adjacent
    'data orchestration',
    'data integration',
    'ingestion pipeline',
    'workflow orchestration',
    'airflow',
    'dagster',
    'prefect',
  ],
  onelake: [
    'onelake',
    'one lake',
    'lakehouse',
    // adjacent / open table formats
    'apache iceberg',
    'iceberg',
    'delta lake',
    'apache hudi',
    'parquet',
    'open table format',
    'data lakehouse',
    'medallion architecture',
  ],
  pipelines: [
    'pipelines',
    'copy activity',
    'eventstream',
    'eventstreams',
    'event stream',
    'orchestration',
    // adjacent
    'kafka',
    'event hubs',
    'streaming ingest',
    'change data capture',
    'cdc',
  ],
  hdinsight: [
    'hdinsight',
    'hd insight',
    // adjacent / managed Hadoop & Spark
    'apache spark',
    'spark sql',
    'spark cluster',
    'managed spark',
    'hadoop',
    'mapreduce',
    'yarn',
    'hbase',
    'apache hive',
  ],
  'service-assist': ['service assist'],
  'power-bi': [
    'power bi',
    'powerbi',
    'pbi',
    // adjacent
    'dax',
    'tabular model',
    'semantic model',
    'business intelligence',
    'self-service bi',
  ],
  'data-lake': [
    'azure data lake',
    'adls',
    'data lake gen2',
    'data lake storage',
    // adjacent
    'object storage',
    'hierarchical namespace',
    'blob storage',
  ],
  synapse: [
    'synapse',
    'azure synapse',
    // adjacent
    'dedicated sql pool',
    'serverless sql',
    'data warehouse',
    'mpp',
  ],
  azure: [
    'azure',
    'microsoft cloud',
    // adjacent
    'azure resource manager',
    'arm template',
    'bicep',
    'entra id',
    'azure ad',
  ],
  'azure-gov': [
    'azure government',
    'azure gov',
    'fedramp',
    'gov cloud',
    'sovereign cloud',
    'dod il',
    // adjacent
    'public sector cloud',
    'cjis',
    'fips 140',
    'high impact level',
    'il5',
    'il6',
  ],
  ai: [
    // models & families
    'gpt',
    'gpt-4',
    'gpt-5',
    'chatgpt',
    'claude',
    'gemini',
    'llama',
    'mistral',
    'phi-3',
    'phi-4',
    'deepseek',
    'qwen',
    // techniques
    'llm',
    'large language model',
    'foundation model',
    'transformer',
    'embedding',
    'vector database',
    'vector search',
    'rag',
    'retrieval augmented',
    'fine-tuning',
    'fine tuning',
    'lora',
    'inference',
    'prompt engineering',
    // products / surfaces
    'azure openai',
    'azure ai',
    'azure ai studio',
    'github copilot',
    'copilot',
    'm365 copilot',
    'agent',
    'ai agent',
    'agentic',
    'mcp',
    'model context protocol',
    // ecosystem
    'huggingface',
    'hugging face',
    'langchain',
    'llamaindex',
    'ollama',
    'nvidia',
    'h100',
    'tpu',
    'gpu cluster',
    // umbrella
    'machine learning',
    ' ml ',
    'artificial intelligence',
    'generative ai',
    'genai',
  ],
  humor: [
    // intentionally narrow — most humor tagging comes from subreddit hints,
    // not keywords. These are just safety-net matches.
    'devs be like',
    'works on my machine',
    'it works',
  ],
};

// Terms that strongly suggest a low-relevance item even if it matched.
export const NOISE_KEYWORDS: string[] = [
  'taylor swift',
  'celebrity',
  'royal',
  'sport',
  'sports',
  'football',
  'horoscope',
  'recipe',
];

// Source-quality bonus (added once per article).
export const SOURCE_QUALITY: Record<string, number> = {
  bbc: 2,
  nyt: 2,
  guardian: 2,
  hn: 1,
  reddit: 0,
};
