import type { ProductChannel, Role } from './types';

// Lowercase keyword lists. Phrases use word-boundary matching in score.ts.
// Tune freely — this file is meant to be edited by the team.

export const ROLE_KEYWORDS: Record<Role, string[]> = {
  manager: [
    'roadmap',
    'strategy',
    'leadership',
    'org',
    'reorg',
    'layoff',
    'hiring',
    'pricing',
    'ga',
    'general availability',
    'announce',
    'announcement',
    'partnership',
    'acquisition',
    'earnings',
    'snowflake',
    'databricks',
    'bigquery',
    'aws',
    'gcp',
    'gartner',
    'forrester',
    'idc',
    'market share',
    'enterprise',
  ],
  developer: [
    'api',
    'sdk',
    'library',
    'framework',
    'release',
    'open source',
    'oss',
    'github',
    'typescript',
    'javascript',
    'python',
    'rust',
    '.net',
    'c#',
    'spark',
    'm language',
    'power query m',
    'dax',
    'connector',
    'performance',
    'benchmark',
    'compiler',
    'runtime',
    'cli',
    'developer experience',
    'devex',
    'tooling',
  ],
  sre: [
    'incident',
    'outage',
    'postmortem',
    'post-mortem',
    'reliability',
    'observability',
    'monitoring',
    'sre',
    'on-call',
    'on call',
    'kubernetes',
    'k8s',
    'scaling',
    'latency',
    'sli',
    'slo',
    'security',
    'cve',
    'vulnerability',
    'patch',
    'azure status',
    'service health',
    'capacity',
    'chaos engineering',
  ],
  pm: [
    'feature',
    'preview',
    'public preview',
    'private preview',
    'general availability',
    'roadmap',
    'customer',
    'use case',
    'case study',
    'analyst',
    'gartner',
    'forrester',
    'competitive',
    'positioning',
    'ux',
    'user research',
    'design',
    'persona',
    'adoption',
    'retention',
    'pricing',
  ],
};

// Product-specific keyword lists. Order doesn't matter; matches are additive.
export const PRODUCT_KEYWORDS: Record<ProductChannel, string[]> = {
  'power-query': [
    'power query',
    'pqo',
    'power query online',
    'm language',
    'm formula',
  ],
  dataflows: ['dataflow', 'dataflows', 'dataflow gen2', 'dataflows gen1'],
  fabric: [
    'microsoft fabric',
    'fabric capacity',
    'fabric workspace',
    'ms fabric',
  ],
  'data-factory': [
    'data factory',
    'adf',
    'azure data factory',
    'fabric data factory',
  ],
  onelake: ['onelake', 'one lake', 'lakehouse'],
  pipelines: [
    'pipelines',
    'copy activity',
    'eventstream',
    'eventstreams',
    'event stream',
    'orchestration',
  ],
  hdinsight: ['hdinsight', 'hd insight'],
  'service-assist': ['service assist'],
  'power-bi': ['power bi', 'powerbi', 'pbi'],
  'data-lake': [
    'azure data lake',
    'adls',
    'data lake gen2',
    'data lake storage',
  ],
  synapse: ['synapse', 'azure synapse'],
  azure: ['azure', 'microsoft cloud'],
  'azure-gov': [
    'azure government',
    'azure gov',
    'fedramp',
    'gov cloud',
    'sovereign cloud',
    'dod il',
  ],
};

// Terms that strongly suggest a low-relevance item even if it matched.
export const NOISE_KEYWORDS: string[] = [
  'taylor swift',
  'celebrity',
  'royal',
  'sport',
  'sports',
  'football',
  'horoscope',
  'recipe',
];

// Source-quality bonus (added once per article).
export const SOURCE_QUALITY: Record<string, number> = {
  bbc: 2,
  guardian: 2,
  hn: 1,
  reddit: 0,
};
